spring.application.name=alert
logging.level.org.springframework=error
# Data store file paths
data.store.path.initial=classpath:data/initial.json
data.store.path.current=file:${user.home}/data/current.json